### ISSUE TITLE
ToIP Specification Theme and Features

### ISSUE THREAD

**Issue by vinomaster** [decentralized-identity/spec-up#11]
The [ToIP Foundation](https://trustoverip.org/) would like to use **spec-up** for the development of deliverables that may be targeted for an SDO. 

#### Authoring

1. Markdown editor agnostic
2. Authors need a simple way to 
	1. get organized -- define a document outline; this can be addressed via a collection of folders containing markdown files that are listed in order in the ```markdown_paths``` property.
	2. Assign work to authors based on outline components

### Must have
1. Styling 
    1. Ability to configure alternative logo in the spec.json file
    2. Ability to configure toc_anchor background color in the spec.json file
    3. Footer for ToIP Foundation
2. Theme Versioning
	1. Github access to uncompiled code if changes are required
	2. [Github Repository Template](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-template-repository) for easy priming of a ToIP repo
3. Development and Processing
	1. Command line tools (make) for generating local test content
	2. Github workflow (actions) for producing GitHub-Pages
4. Rendering Formats
	1. Single Markdown file (via pandoc or other plugins): n to 1 -- multiple ```markdown_paths``` files combined into a single markdown file. 
	2. Single PDF (via pdf-export or other plugins)
	3. Website/GitHub-Pages

### Should have
1. Styling 
    1. Search suggest feature as [demonstrated here](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions)
    2. Search highlight feature as [demonstrated here](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting)
2. Development and Processing
	1. Command line tool (make or scripts) for generating local test content

**Comment by csuwildcat** [comment]
I believe the only outstanding ones we need to add to the project are:

1. The color/theme items
2. PDF generation
3. Search features

**Comment by vinomaster** [comment]
Have a look at this [new repo](https://github.com/trustoverip/spec-up) as it addresses many of the reqs. It is not perfect but is does allow the ToIP community to tackle their tasks.  Missing still is Search but that is not a show stopper. 

I had to make some changes to the workflow action plus this repo now allows for a local docker env so that the contributors do not need to install many of the dependencies.  I suspect many of these changes would not be of interest but you may want to have a look...

**Comment by csuwildcat** [comment]
@vinomaster I added some nice new features since that you might want to pull in, but I will take a look at your repo and see about the content we can pull in. Going to close this ticket for now.

**Comment by csuwildcat** [comment]
@vinomaster just noticed the PDF thing wasn't done - could you open specific tickets for the few remaining items?

**Comment by vinomaster** [comment]
No worries will do. FYI .. I handled PDF see ```make publish``` [here](https://github.com/trustoverip/spec-up/blob/main/Makefile)
