### ISSUE TITLE
Markdown_Paths Array fails if larger than 5 items

### ISSUE THREAD

**Issue by vinomaster** [decentralized-identity/spec-up#13]
The `npm run render` command will succeed but generate an empty `index.html` if the `markdown_path[]` is larger than 5 items:

This works:
```
"markdown_paths": [
        "header.md",
        "abstract.md",
        "summary.md",
        "motivation.md",
        "scope.md"
      ],
```

This does not:
```
"markdown_paths": [
        "header.md",
        "abstract.md",
        "summary.md",
        "motivation.md",
        "scope.md".
        "introduction.md
      ],
```

**Comment by csuwildcat** [comment]
I'm suspect about this, because we have two other specs using the tool with 15+ files and it runs fine. It see a period instead of a comma on your fourth item, could that be causing the json to be invalid?

**Comment by csuwildcat** [comment]
Zooming in:

![Screenshot_20201217-194020~2](https://user-images.githubusercontent.com/131786/102572029-e885e980-409f-11eb-8f75-f5c6ff195129.jpg)

**Comment by vinomaster** [comment]
Agreed. Fixed. Thanks.
