### ISSUE TITLE
Feature request: permanent URLs for each specific release

### ISSUE THREAD

**Issue by bumblefudge** [decentralized-identity/spec-up#28]
[Inelegant workarounds](https://github.com/decentralized-identity/waci-presentation-exchange/pull/131/files) will proliferate if working groups have trouble doing archival versioning

ideally, these URLs would be static:
i.f/{specname}/ = today's draft
i.f/{specname}/v/X.X = each number draft
i.f/{specname}/v/latest = most recent numbered draft

**Comment by csuwildcat** [comment]
From a Spec-Up angle, how would you all want to handle this? Today you can generate a copy under any path you want, just need to change the paths to what you suggested above. If folks want some other feature, what would you expect the editor/user experience to be?

**Comment by bumblefudge** [comment]
Oh, good point-- I didn't even think to look up [how PresEx did it](https://github.com/decentralized-identity/presentation-exchange/blob/master/specs.json) at the time! I will attempt a PR making a similar v0.1 subdirectory in WACI-PEx.
