### ISSUE TITLE
Cannot include references of RFCs above RFC8910

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/spec-up#56]
For some reason, spec-up does not render any IETF RFCs above RFC8910.

Do you have to publish a new version of spec-up to support this?

**Comment by awoie** [comment]
@csuwildcat @decentralgabe can you help with this?

**Comment by darrellodonnell** [comment]
`/assets/compiled/refs.json` needs to be updated for this @awoie 

Any idea where that was compiled from?

**Comment by darrellodonnell** [comment]
fwiw the current files appear to be maintained here: https://github.com/tobie/specref/tree/main/refs
