### ISSUE TITLE
How to include normative references that are not W3C, IETF and WHATWG?

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/spec-up#57]
If I have ISO docs, how would I include them in the normative references table?

**Comment by awoie** [comment]
@csuwildcat @decentralgabe Can either of you help?

**Comment by decentralgabe** [comment]
@awoie I usually manually add in references using `[[ref: ... ]]`

@csuwildcat would need to add something to the processing to pull in ISO docs I believe

**Comment by awoie** [comment]
> @awoie I usually manually add in references using `[[ref: ... ]]`

@decentralgabe can you give an example? I cannot find anything related to this in the docs.

**Comment by decentralgabe** [comment]
yes, see the references here for ed25519 and a few others that aren't a part of a group -- https://did-dht.com/#references

https://github.com/TBD54566975/did-dht-method/blob/main/spec/spec.md#references

**Comment by awoie** [comment]
> https://github.com/TBD54566975/did-dht-method/blob/main/spec/spec.md#references

Thank you so much. We should add that to the example spec/docs. This is would be very useful.
