### ISSUE TITLE
Version 0.10.7 doesn't have latest code

### ISSUE THREAD

**Issue by brianorwhatever** [decentralized-identity/spec-up#64]
After #59 was merged the npm package that was uploaded as 0.10.7 doesn't have the latest code. Was there another step required @csuwildcat?

**Comment by csuwildcat** [comment]
No, probably was just moving too quickly, I'll take a look today

**Comment by brianorwhatever** [comment]
that would great, thanks!

**Comment by brianorwhatever** [comment]
@csuwildcat can you take a look at publishing the code?

**Comment by darrellodonnell** [comment]
Any updates here?

**Comment by csuwildcat** [comment]
@darrellodonnell @brianorwhatever sorry for the long delay, does this 0.10.8 now include it from what you see: https://www.npmjs.com/package/spec-up

**Comment by brianorwhatever** [comment]
Yeah, looks good. Thanks @csuwildcat!

**Comment by darrellodonnell** [comment]
I've deployed it in a couple of repos now. Many thanks @csuwildcat @brianorwhatever
